---
- name: "Replace Nginx config"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"

- name: "Allow Web on firewall"
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - https
    - http

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: "Start and enable Nginx"
  service:
    name: nginx.service
    enabled: yes
    state: restarted